apiVersion: v1
kind: Pod
metadata:
  name: deis-monitor-grafana-proxy
  namespace: deis
  labels:
    heritage: deis
spec:
  containers:
  - name: grafana
    image: gcr.io/google_containers/proxy-to-service:v2
    args: [ "tcp", "3500", "deis-monitor-grafana.deis.svc.cluster.local" ]
    ports:
    - name: http-ui
      protocol: TCP
      containerPort: 3500
      hostPort: 3500
