apiVersion: v1
kind: Service
metadata:
  name: deis-monitor-grafana
  namespace: deis
  labels:
    heritage: deis
    app: deis-monitor-grafana
spec:
  ports:
  - port: 3500
    name: ui
    targetPort: ui
  selector:
    app: deis-monitor-grafana
