apiVersion: v1
kind: Pod
metadata:
  name: deis-monitor-chronograf-proxy
  namespace: deis
  labels:
    heritage: deis
spec:
  containers:
  - name: http-ui
    image: gcr.io/google_containers/proxy-to-service:v2
    args: [ "tcp", "10000", "deis-monitor-chronograf.deis.svc.cluster.local" ]
    ports:
    - name: http-ui
      protocol: TCP
      containerPort: 10000
      hostPort: 10000
