apiVersion: v1
kind: Service
metadata:
  name: deis-monitor-chronograf
  namespace: deis
  labels:
    heritage: deis
    app: deis-monitor-chronograf
spec:
  ports:
  - port: 10000
    name: admin
    targetPort: admin
  selector:
    app: deis-monitor-chronograf
