apiVersion: v1
kind: Service
metadata:
  name: deis-monitor-influxdb
  namespace: deis
  labels:
    heritage: deis
    app: deis-monitor-influxdb
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: influx
    router.deis.io/connectTimeout: "10"
    router.deis.io/tcpTimeout: "1200"
spec:
  ports:
  - port: 80
    name: admin
    targetPort: admin
  - port: 8086
    name: transport
    targetPort: transport
    protocol: TCP
  - port: 8084
    name: ssltransport
    targetPort: ssltransport
    protocol: TCP
  selector:
    app: deis-monitor-influxdb