grafana:
  org: "deisci"
  pull_policy: "Always"
  docker_tag: canary
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 5Gi
influxdb:
  org: "deisci"
  pull_policy: "Always"
  docker_tag: canary
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
  url: "my.influx.url"
  database: "kubernetes"
  user: "user"
  password: "password"
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 20Gi
telegraf:
  org: "deisci"
  pull_policy: "Always"
  docker_tag: canary
  # limits_cpu: "100m"
  # limits_memory: "50Mi"

global:
  # Set the location of Workflow's influxdb cluster
  #
  # Valid values are:
  # - on-cluster: Run Influxdb within the Kubernetes cluster
  # - off-cluster: Influxdb is running outside of the cluster and credentials and connection information will be provided.
  influxdb_location: "on-cluster"
  # Set the location of Workflow's grafana instance
  #
  # Valid values are:
  # - on-cluster: Run Grafana within the Kubernetes cluster
  # - off-cluster: Grafana is running outside of the cluster
  grafana_location: "on-cluster"
