grafana:
  org: "deisci"
  pull_policy: "Always"
  docker_tag: canary
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
influxdb:
  org: "deisci"
  pull_policy: "Always"
  docker_tag: canary
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
telegraf:
  org: "deisci"
  pull_policy: "Always"
  docker_tag: canary
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
