name: telegraf
home: https://github.com/teamhephy/monitor/tree/master/telegraf
version: <Will be populated by the ci before publishing the chart>
description: Monitoring for Deis Workflow.
maintainers:
  - email: team@teamhephy.com
